config/routes.rb
Rails.application.routes.draw do
  root "notes#index"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: "sessions#logout"
  get 'sessions/login'
  get 'users/create'

  resources :users  do
    resources :notes do
      get :share_note, on: :collection
      post :save_sharing
      get :edit_permissions
      get :change_permissions, on: :collection
      post :update_permissions
      resources :tags do
        get :add_tag, on: :collection
      end

    end
  end


  # resources :notes do
  # end
  #
  # resources :tags do
  # end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :shared_notes, dependent: :destroy
  has_many :tags, dependent: :destroy
end

app/models/shared_note.rb
class SharedNote < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :notes, dependent: :destroy
  has_many :shared_notes, dependent: :destroy
  validates :username, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :info, :error, :warning, :success

  helper_method :current_user
  helper_method :logged_in?
  before_action :authorized

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :get_user

  def index
    @user_notes = @user.notes
    shared_notes = SharedNote.where(shared_user_id: @user.id)
    @notes_ids = shared_notes.pluck(:note_id)
    @user_shared_notes = Note.all.find(@notes_ids)
  end

  def new
    @note = Note.new
  end

  def create
    @note = @user.notes.create(title: params[:note][:title], body: params[:note][:body])
    flash[:danger] = "Created note successfully!"
    redirect_to user_notes_path(@user.id)
  end

  def edit
    @note = Note.find(params[:id])
  end

  def show
    @note = Note.find(params[:id])
    @tags = @note.tags
  end

  def update
    @note = Note.find(params[:id])
    @note.update(title: params[:note][:title], body: params[:note][:body])
    flash[:notice] = "Note has updated successfully!"
    redirect_to user_notes_path(@user.id)
  end

  def edit_permissions
    # @shared_permissions = {}
    @note = Note.find(params[:note_id])
    @shared_notes = @note.shared_notes
  end

  def change_permissions
    @note = Note.find(params[:note_id])
    @note_user = User.find(params[:user_id])
    @permission = params[:permission]
    respond_to do |format|
			format.js
		end
  end

  def update_permissions
    @note = Note.find(params[:note_id])
    @note_user = User.find(params[:user])
    @note.shared_notes.where(permissions: params["note_permission"], shared_user_id: @note_user.id, user_id: @user.id).first.update(permissions: params[:new_permission])
    if params[:note_permission] == "owner"
      shared_users = @note_user.shared_notes.where(note_id: @note.id, permissions: "owner")
      if shared_users.present?
        shared_users.all.each do |sh_note|
          sh_note.update(permissions: params[:new_permission])
        end
      end
    elsif (params[:note_permission] == "update" && params[:new_permission] == "read")
      shared_users = @note_user.shared_notes.where(note_id: @note.id, permissions: "update")
      if shared_users.present?
        shared_users.all.each do |sh_note|
          sh_note.update(permissions: params[:new_permission])
        end
      end
    else
    end
    flash[:notice] = "Note permission has updated for the user: #{@note_user.username}"
    redirect_to user_note_edit_permissions_path(note_id: @note.id)
  end


  def share_note
    @note = Note.find(params[:note_id])
    respond_to do |format|
			format.js
		end
  end

  def save_sharing
    @note = Note.find(params[:note_id])
    users, non_exist_users=[],[]
    params["user_emails"].split(",").each do |email|
      user = User.find_by(username: email.strip)
      if user.present?
        @user.shared_notes.create(note_id: @note.id, shared_user_id: user.id, permissions: params[:permission])
      else
        non_exist_users.push email
      end
    end
    if non_exist_users.present?
      flash[:notice] = "Skipped sharing note to non exsting users.. #{non_exist_users}"
    else
      flash[:notice] = "Note has shared for the selected users successfully!"
    end
    redirect_to user_notes_path(@user.id)
  end

  def destroy
    @note = Note.find(params[:id])
    if params[:remove_user_note] == "true"
      shared_user = User.find(params[:user_id])
      SharedNote.where(note_id: @note.id, shared_user_id: shared_user.id).first.delete
      shared_user.shared_notes.where(note_id: @note.id).delete_all
      flash[:notice] = "Note has been removed for the user and shared users successfully!"
    else
      SharedNote.where(note_id: @note.id).delete_all
      @note.destroy if @note.present?
      flash[:notice] = "Note deleted successfully!"
    end
    redirect_to user_notes_path(@user.id)
  end

  private
    def get_user
      @user = User.find(session[:user_id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]
  def new
  end

  def logout
    session.clear
    redirect_to '/welcome'
  end

  def login

  end

  def welcome

  end

  def create
    if !params[:password].present?
      flash[:notice] = "Please enter email"
      redirect_to "/welcome" and return
    elsif !params[:username].present?
      flash[:notice] = "Please enter password!"
      redirect_to "/welcome" and return
    end

    @user = User.find_by(username: params[:username])
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Notes Application."
      redirect_to user_notes_path(@user.id)
    else
      flash[:notice] = "User doesn't exist!"
      redirect_to "/welcome"
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :get_user
  def add_tag
    @tag = Tag.new
    @note = Note.find(params[:note_id])
    respond_to do |format|
			format.js
		end
  end

  def create
    @note = Note.find(params[:note_id])
    @note.tags.create(tag: params[:tag][:tag], name: @user.username)
    flash[:notice] = "Tag has created for the note successfully!"
    redirect_to user_notes_path(@user.id)
  end

  private
  def get_user
    @user = User.find(session[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.create(username: params[:user][:username], password_digest: params[:user][:password])
    if @user.errors.present?
      flash[:notice] = "Please Enter valid Email format!"
      redirect_to '/users/new'
    else
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Notes dashboard!"
      redirect_to user_notes_path(@user.id)
    end
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div class = "row alert-flash">
  <div class = "col-sm-2"></div>
  <div class = "alert-flash col-sm-8 text-center">
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- <div class="footer">
  <h3><strong> Notes Application</strong></h3>
</div>

<style>
.footer {
   position: absolute;
   left: 0;
   bottom: 0;
   height: 10%;
   width: 100%;
   background-color: #a8a88e;
   color: #aa3434;
   text-align: center;
}
</style> -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" style="background-color:#a8a88e">
  <div class="container-fluid">
    <div class="navbar-header pl-3">
      <ul class="nav navbar-nav">
        <% if current_user.present? %>
          <ul style="background-color:#aa3434" class="nav navbar-nav pt-3">
            <li><a href="<%=user_notes_path(current_user.id)%>">Notes Dashboard</a></li>
          </ul>
          <ul style="background-color:black" class="nav navbar-nav">
            <li><a href="<%=logout_path%>">Logout</a></li>
          </ul>
          <ul style="background-color:white;" class="nav navbar-nav text-right"><li><a>Loggedin as: <%=current_user.username %></a></li></ul>
        <% end %>

      </ul>



    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet"></link>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= render partial: 'layouts/flash' unless flash.nil? || flash.empty? %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
    <br><br>
  </body>


<script>
  $(".alert-flash" ).fadeOut(3000);
  </script>
</html>

app/views/notes/_change_permissions.html.erb
<div class="modal position-relative" id="change-permissions-info-modal">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header text-light">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-danger">
          Change permissions for the user <%=@note_user.username %> to the note: <%= @note.title %>
        </h4>
      </div>
      <div class="modal-body">
        <%= form_with url: user_note_update_permissions_path(user: @note_user.id,note_id: @note.id), method: :post do  |f|%>
        <div class = "alert alert-info"><strong>This user has the "<%=@permission.upcase %>" permission for this note.</strong> </div>
            <input type = "hidden" name = "note_permission" value= '<%=@permission%>' %>
            <div class = "row form-group">
              <div class = "col-sm-4"></div>
              <div class = "col-sm-4 text-center">
                <select id= "new_permission" name="new_permission" class="form-control">
                  <option value = ""> Select Permission</option>
                  <option value = "read"> Read</option>
                  <option value = "update"> Update</option>
                  <option value = "owner"> Owner</option>

                </select>
                </div>

              </div>
              <div class = "row form-group">
              <div class = "col-sm-6 text-right">
               <%= f.submit class: "btn btn-primary", value: "Share"%>
               </div>
               <div class = "col-sm-4 text-left">
               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
              </div>
            <%end%>
          </div>
          </div>
      </div>

      </div>
<script>
$(document).ready(function(){
  $("#new_permission").val('<%=@permission%>')
})

</script>

app/views/notes/_form.html.erb
<%= form_for [@user, @user.notes.build] do  |f|%>
<div class = "row form-group">
  <div class = "col">
  <%= f.text_field :title, :required => true, placeholder: "Enter Title", class: "form-control"%><br>
  </div>
</div>

<div class = "row form-group">
  <div class = "col">
    <%= f.text_area :body, :required => true, placeholder: "Enter Text", class: "form-control"%><br>
  </div>
</div>

<div class = "row form-group">
<div class = "col text-center">
 <%= f.submit class: "form-control btn btn-primary"%>
</div>
</div>
<%end%>

app/views/notes/_share_note.html.erb
<div class="modal position-relative" id="share-note-info-modal">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header text-light">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">
          Share note: <%= @note.title %>
        </h3>
      </div>
      <div class="modal-body">
        <div class = "row text-center pl-3">
          <div class = "col-sm-3"></div>
          <div class = "col-sm">
            <%= form_with url: user_note_save_sharing_path(@user.id,@note.id), method: :post do  |f|%>
              <div class = "row form-group">
                <div class="row mr-3">
                  <div class="col-sm-6">
                    <textarea id= "user_emails" name="user_emails" placeholder: "Enter Emails with comma separated.." class="form-control"/>
                  </div>
                </div>
                </div>
                <div class = "row form-group">
                  <div class = "col-sm-4"></div>
                  <div class = "col-sm-4 text-center">
                    <select id= "permission" name="permission" class="form-control">
                      <option value = ""> Select Permission</option>
                      <option value = "read"> Read</option>
                      <option value = "update"> Update</option>
                      <option value = "owner"> Owner</option>

                    </select>
                    </div>

                  </div>
                  <div class = "row form-group">
                  <div class = "col-sm-6 text-right">
                   <%= f.submit class: "btn btn-primary", value: "Share"%>
                   </div>
                   <div class = "col-sm-4 text-left">
                   <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                  </div>
                <%end%>
          </div>
          </div>
      </div>

      </div>
    </div>
  </div>

app/views/notes/change_permissions.js.erb
$('#change-permissions-modal').html('<%= escape_javascript(render partial: 'change_permissions') %>')
$('#change-permissions-info-modal').show();
$("#change-permissions-info-modal").click(function(ev) {
    if(ev.target != this) return;
    $('#change-permissions-info-modal').hide();
  });
$('button[data-dismiss="modal"]').click(function(){
     $('#change-permissions-info-modal').hide();
 })

app/views/notes/edit.html.erb
<div class = "container">
  <div class = "row">
   <div class = "row">
     <div class = "col-sm-2"></div>
     <div class = "col-sm-8">
       <h1>Edit note- <%=@note.title%></h1>
       <%= form_with model: [@user, @note], url: user_note_path(user_id: @user.id, id: @note.id), method: :put do  |f|%>
       <div class = "row form-group">
         <div class = "col">
         <%=f.text_field :title, :required => true, placeholder: "Enter Title", class: "form-control"%><br>
         </div>
       </div>

       <div class = "row form-group">
         <div class = "col">
           <%=f.text_area :body, :required => true, placeholder: "Enter Text", class: "form-control"%><br>
         </div>
       </div>

       <div class = "row form-group">
       <div class = "col text-center">
        <%= f.submit class: "form-control btn btn-primary"%>
       </div>
       </div>
       <%end%>

      </div>
     </div>
 </div>
 <br>
 <br>
 <div class = "row">
   <div class = "col text-center">
     <div class = "col-sm-6 text-left">
       <a href= "<%= user_notes_path(@user.id) %>", class = "btn btn-danger rounded-0">BACK</a>
     </div>

   </div>
   </div>
</div>

app/views/notes/edit_permissions.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col">
      <h3 class = "text-info"> Edit permissions for the note: <%=@note.title %></h3>
      <div class = "row">
        <table class="table table-stripped" id="permissions-info-table">
          <thead>
            <tr>
              <th>Username</th>
              <th>Permissions</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr style="bg-color:red">
              <td class="text-danger"><%=User.find(@note.user_id).username%></td>
              <td class="text-danger"><%="owner".capitalize%></td>
              <td>
                <%= '<i class="fa fa-edit text-warning pr-3 disabled" style= "font-size: 22px;"></i>'.html_safe%>
              </td>

            </tr>
            <% @shared_notes.each do |note| %>

              <tr>
                <td class="text-info"><%=User.find(note.shared_user_id).username%></td>
                <td><%=note.permissions.capitalize%></td>
                <td>
                  <% if @user.id == note.shared_user_id %>
                    <%= '<i class="fa fa-edit text-warning pr-3 disabled" style= "font-size: 22px;"></i>'.html_safe%>
                  <% else %>
                    <%= link_to '<i class="fa fa-edit text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, change_permissions_user_notes_path(note_id: @note.id, user_id: note.shared_user_id, permission: note.permissions), remote: true, 'data-toggle': 'modal', 'data-target': "#change-permissions-modal"%>
                    <%= link_to '<i class="fa fa-trash text-danger pr-3" style= "font-size: 22px;"></i>'.html_safe, user_note_path(note.shared_user_id, @note.id, remove_user_note: true, permission: note.permissions), method: :delete, data: {confirm: "Are you sure, you want to remove '#{User.find(note.shared_user_id).username}' this note?"}, title: 'Remove User from Note', class: "text-danger" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </table>
      </div>
    </div>
    <br>
    <br>
    <div class = "row">
        <div class = "col-sm text-left">
          <a href= "<%= user_notes_path(@user.id) %>", class = "btn btn-success rounded-0">Back</a>
        </div>
      </div>
  </div>
  <div class = "row">
    <div id = "change-permissions-modal"></div>
    </div>
  </div>
  <script>
    $('#permissions-info-table').DataTable({

    });
    </script>

app/views/notes/index.html.erb
<div class = "container">
  <div class = "row">
  <h3 class>Note Details:</h3>
  <table class="table table-hover table-responsive" id="notes-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th class = "text-center">Tags Count</th>
        <th class = "text-center"> Edit Permissions</th>
        <th class = "text-center"> Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @user_notes.each do |note| %>
        <tr>
          <td><%=note.title%></td>
          <td class="multiline-ellipsis"><%=note.body%></td>
          <td class = "text-center"><%= note.tags.count %></td>
          <td class = "text-center">
            <%= link_to '<i class="fa fa-lock text-danger pr-3" style= "font-size: 22px;"></i>'.html_safe, user_note_edit_permissions_path(@user.id, note.id), title: 'Edit Note Permissions for the Users', class: "text-danger"%>
          </td>
          <td class = "text-center">
            <div class = "row">
              <%= link_to '<i class="fa fa-info text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, user_note_path(@user.id,note), title: 'Note Details', class: "text-danger" %>
              <%= link_to '<i class="fa fa-edit text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, edit_user_note_path(@user.id,note), title: 'Edit Note', class: "text-danger" %>
              <%= link_to '<i class="fa fa-comments text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, add_tag_user_note_tags_path(@user.id, note), title: 'Add Tag', class: "text-danger", remote: true, 'data-toggle': 'modal', 'data-target': "#add-tag-modal" %>
              <%= link_to '<i class="fa fa-users text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, share_note_user_notes_path(@user.id, note_id: note.id), title: 'Share Note', class: "text-danger", remote: true, 'data-toggle': 'modal', 'data-target': "#share-note-modal" %>
              <%= link_to '<i class="fa fa-trash text-danger pr-3" style= "font-size: 22px;"></i>'.html_safe, user_note_path(@user.id, note), method: :delete, data: {confirm: "Are you sure, you want to delete '#{note.title.titleize}' this note?"}, title: 'Delete Note', class: "text-danger" %>
            </div>
          </td>
        </tr>
        <% end %>
        <% @user_shared_notes.each do |note| %>
          <tr>
            <td><%=note.title%></td>
            <td class="multiline-ellipsis"><%=note.body%></td>
            <td class = "text-center"><%= note.tags.count %></td>
            <td class = "text-center">
              <%= link_to '<i class="fa fa-lock text-danger pr-3" style= "font-size: 22px;"></i>'.html_safe, user_note_edit_permissions_path(@user.id, note.id), title: 'Edit Note Permissions for the Users', class: "text-danger"%>
            </td>
            <td class = "text-center">
              <% permission = SharedNote.where(note_id: note.id, shared_user_id: @user.id).first.permissions %>
              <div class = "row">
              <% if permission == "owner" %>
                <%= link_to '<i class="fa fa-info text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, user_note_path(@user.id,note), title: 'Note Details', class: "text-danger" %>
                <%= link_to '<i class="fa fa-edit text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, edit_user_note_path(@user.id,note), title: 'Edit Note', class: "text-danger" %>
                <%= link_to '<i class="fa fa-comments text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, add_tag_user_note_tags_path(@user.id, note), title: 'Add Tag', class: "text-danger", remote: true, 'data-toggle': 'modal', 'data-target': "#add-tag-modal" %>
                <%= link_to '<i class="fa fa-users text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, share_note_user_notes_path(@user.id, note_id: note.id), title: 'Share Note', class: "text-danger", remote: true, 'data-toggle': 'modal', 'data-target': "#share-note-modal" %>
                <%= link_to '<i class="fa fa-trash text-danger pr-3" style= "font-size: 22px;"></i>'.html_safe, user_note_path(@user.id, note), method: :delete, data: {confirm: "Are you sure, you want to delete '#{note.title.titleize}' this note?"}, title: 'Delete Note', class: "text-danger" %>
              <% elsif (permission == "update") %>
                <%= link_to '<i class="fa fa-info text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, user_note_path(@user.id,note), title: 'Note Details', class: "text-danger" %>
                <%= link_to '<i class="fa fa-edit text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, edit_user_note_path(@user.id,note), title: 'Edit Note', class: "text-danger" %>
                <%= link_to '<i class="fa fa-comments text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, add_tag_user_note_tags_path(@user.id, note), title: 'Add Tag', class: "text-danger", remote: true, 'data-toggle': 'modal', 'data-target': "#add-tag-modal" %>
            <% else %>
              <%= link_to '<i class="fa fa-info text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, user_note_path(@user.id,note), title: 'Note Details', class: "text-danger" %>
              <%= link_to '<i class="fa fa-comments text-primary pr-3" style= "font-size: 22px;"></i>'.html_safe, add_tag_user_note_tags_path(@user.id, note), title: 'Add Tag', class: "text-danger", remote: true, 'data-toggle': 'modal', 'data-target': "#add-tag-modal" %>

            <% end %>
            </div>
            </td>
          </tr>
      <% end %>

<div class="row">
  <div id = "add-tag-modal"></div>
  </div>
  <div class="row">
    <div id = "share-note-modal"></div>
    </div>

    </tbody>
  </table>
  </div>

  <br>
  <br>
  <div class = "row">
      <div class = "col-sm text-left">
        <a href= "<%= new_user_note_path(@user.id) %>", class = "btn btn-success btn-block rounded-0">Add note</a>
      </div>
    </div>
  </div>

  <style>
    .multiline-ellipsis {
      max-width: 550px;
      overflow: hidden;
      -webkit-line-clamp: 4;
      display: -webkit-box;
      -webkit-box-orient: vertical;
      line-height: 1.9rem;
      padding-bottom: 0rem !important;
    }

    td.multiline-ellipsis {
      padding-bottom: 4px !important;
      text-align: left;
    }
    </style>

  <script>
    $('#notes-table').DataTable({

    });
    </script>

app/views/notes/new.html.erb
<div class = "container">
  <div class = "row">
   <div class = "row">
     <div class = "col-sm-2"></div>
     <div class = "col-sm-8">
       <h1>Add new note</h1>
        <%= render partial: 'form' %>
      </div>
     </div>
 </div>
</div>

app/views/notes/share_note.js.erb
$('#share-note-modal').html('<%= escape_javascript(render partial: 'share_note', locals: {note: @note}) %>')
$('#share-note-info-modal').show();
$("#share-note-info-modal").click(function(ev) {
    if(ev.target != this) return;
    $('#share-note-info-modal').hide();
  });
$('button[data-dismiss="modal"]').click(function(){
     $('#share-note-info-modal').hide();
 })

app/views/tags/_add_tag.html.erb
<div class="modal position-relative" id="add-tag-info-modal">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header text-light">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">
          Add tag for note: <%= @note.title %>
        </h3>
      </div>
      <div class="modal-body">
        <div class = "row text-center">
          <%= form_with model: [@user, @note, @tag], url: user_note_tags_path(user_id: @user.id, id: @note.id), method: :post do  |f|%>
          <div class = "row pl-3 form-group">
            <div class = "col-sm-3 text-center"></div>
            <div class = "col-sm-7 text-center">
            <%= f.text_area :tag, :required => true, placeholder: "Enter Title", class: "form-control pl-3"%><br>
            </div>
          </div>

          <div class = "row form-group">
          <div class = "col-sm-6 text-right">
           <%= f.submit class: "btn btn-primary"%>
           </div>
           <div class = "col-sm-4 text-left">
           <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
          </div>
          <%end%>
          </div>
          </div>

      </div>
    </div>
  </div>
</div>

app/views/tags/add_tag.js.erb
$('#add-tag-modal').html('<%= escape_javascript(render partial: 'add_tag', locals: {note: @note}) %>')
$('#add-tag-info-modal').show();
$("#add-tag-info-modal").click(function(ev) {
    if(ev.target != this) return;
    $('#add-tag-info-modal').hide();
  });
$('button[data-dismiss="modal"]').click(function(){
     $('#add-tag-info-modal').hide();
 })

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>